/**
 * Exercise bank — past-exam problems + frontistiria.
 *
 * SCOPE NOTE
 * ----------
 * The original NKUA past-exam papers (all under `material/exercises/`) are
 * scanned images / hand-set typography with no extractable text. We can't
 * mechanically transcribe them. So this bank is, for now, an *index* of
 * every original artifact:
 *
 *   - One entry per past-exam paper (multi-problem) and per frontistirio.
 *   - `statement` and `solution` are `null` — the UI falls back to the
 *     "Άνοιξε το πρωτότυπο" link to `sourceFile`.
 *   - `prerequisites` is inferred from the date of the paper (everything
 *     up to that point in the academic year was fair game) or, for
 *     frontistiria, from the slide-deck title we extracted.
 *
 * As we transcribe problems lecture-by-lecture, replace the paper-level
 * entries with per-problem ones (one card per «ΘΕΜΑ» / «Άσκηση»). The shape
 * is ready: id, title, problemNumber, weight, statement, solution.
 *
 * BADGES
 * ------
 * 2024 / 2025 sources are surfaced with the «Θέμα Εξετάσεων 2024/2025»
 * badge — see `RECENT_SOURCES` in `types.ts` and the `<ExerciseCard>`
 * rendering. They sort first in the practice hub.
 */

import type { Exercise } from './types'

/**
 * Every lecture slug, in order. Used so a paper that hits "all lectures"
 * doesn't need to enumerate 17 strings by hand.
 */
const ALL_LECTURES = [
  'lectures/L01-eisagogika',
  'lectures/L02-asymptotic-analysis',
  'lectures/L03-divide-and-conquer-i',
  'lectures/L04-divide-and-conquer-ii',
  'lectures/L05-divide-and-conquer-iii',
  'lectures/L06-graphs-i',
  'lectures/L07-graphs-ii',
  'lectures/L08-graphs-iii',
  'lectures/L09-graphs-iv',
  'lectures/L10-data-structures',
  'lectures/L11-greedy-i',
  'lectures/L12-greedy-ii',
  'lectures/L13-greedy-iii',
  'lectures/L14-dp-i',
  'lectures/L15-dp-ii',
  'lectures/L16-dp-iii',
  'lectures/L17-dp-iv',
]

export const EXERCISES: Exercise[] = [
  // ═══════════════════════════════════════════════════════════════════════
  // ΦΡΟΝΤΙΣΤΗΡΙΑ 2023–24 (Έφη Μαλέσιου) — topic-scoped, ordered like the syllabus
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'frontistirio-f1',
    title: 'Φροντιστήριο 1 · Ασυμπτωτικός συμβολισμός (1/2)',
    topic: 'asymptotics',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F1',
    difficulty: 'easy',
    prerequisites: ['lectures/L02-asymptotic-analysis'],
    sourceFile: '/material/exercises/inclass/F1__2023_24__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f2',
    title: 'Φροντιστήριο 2 · Ασυμπτωτικός συμβολισμός (2/2)',
    topic: 'asymptotics',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F2',
    difficulty: 'medium',
    prerequisites: ['lectures/L02-asymptotic-analysis'],
    sourceFile: '/material/exercises/inclass/F2__2023_24.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f3',
    title: 'Φροντιστήριο 3 · Διαίρει και Κυρίευε',
    topic: 'divide-conquer',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F3',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L03-divide-and-conquer-i',
      'lectures/L04-divide-and-conquer-ii',
    ],
    sourceFile: '/material/exercises/inclass/F3__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f4',
    title: 'Φροντιστήριο 4 · Διαίρει και Κυρίευε (2/2)',
    topic: 'divide-conquer',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F4',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L03-divide-and-conquer-i',
      'lectures/L04-divide-and-conquer-ii',
      'lectures/L05-divide-and-conquer-iii',
    ],
    sourceFile: '/material/exercises/inclass/F4__2023_24__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f5',
    title: 'Φροντιστήριο 5 · Αναζήτηση, ταξινόμηση και γραφήματα',
    topic: 'graphs',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F5',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L05-divide-and-conquer-iii',
      'lectures/L06-graphs-i',
    ],
    sourceFile: '/material/exercises/inclass/F5__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f7',
    title: 'Φροντιστήριο 7 · Άπληστοι Αλγόριθμοι (1/2)',
    topic: 'greedy',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F7',
    difficulty: 'medium',
    prerequisites: ['lectures/L11-greedy-i'],
    sourceFile: '/material/exercises/inclass/F7__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f8',
    title: 'Φροντιστήριο 8 · Άπληστοι Αλγόριθμοι (2/2)',
    topic: 'greedy',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F8',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L11-greedy-i',
      'lectures/L12-greedy-ii',
      'lectures/L13-greedy-iii',
    ],
    sourceFile: '/material/exercises/inclass/F8__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f9',
    title: 'Φροντιστήριο 9 · Δυναμικός προγραμματισμός (1/2)',
    topic: 'dp',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F9',
    difficulty: 'medium',
    prerequisites: ['lectures/L14-dp-i'],
    sourceFile: '/material/exercises/inclass/F9__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f10',
    title: 'Φροντιστήριο 10 · Δυναμικός προγραμματισμός (2/2)',
    topic: 'dp',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F10',
    difficulty: 'hard',
    prerequisites: [
      'lectures/L14-dp-i',
      'lectures/L15-dp-ii',
      'lectures/L16-dp-iii',
      'lectures/L17-dp-iv',
    ],
    sourceFile: '/material/exercises/inclass/F10__eclass.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-f11',
    title: 'Φροντιστήριο 11 · Επανάληψη (τελευταίο)',
    topic: 'dp',
    origin: 'frontistirio',
    source: 'frontistirio-2023-24',
    problemNumber: 'F11',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/inclass/F11__eclass.pdf',
    statement: null,
    solution: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Παλαιότερα φροντιστήρια (CamScanner — image-only)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'frontistirio-old-1',
    title: '1ο Φροντιστήριο (παλαιότερο)',
    topic: 'asymptotics',
    origin: 'frontistirio',
    source: 'frontistirio-misc',
    difficulty: 'easy',
    prerequisites: [
      'lectures/L01-eisagogika',
      'lectures/L02-asymptotic-analysis',
    ],
    sourceFile: '/material/exercises/inclass/1%CE%BF%20%CE%A6%CF%81%CE%BF%CE%BD%CF%84.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-old-2',
    title: '2ο Φροντιστήριο (παλαιότερο)',
    topic: 'divide-conquer',
    origin: 'frontistirio',
    source: 'frontistirio-misc',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L03-divide-and-conquer-i',
      'lectures/L04-divide-and-conquer-ii',
    ],
    sourceFile: '/material/exercises/inclass/2%CE%BF%20%CE%A6%CF%81%CE%BF%CE%BD%CF%84.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'frontistirio-old-3',
    title: '3ο Φροντιστήριο (παλαιότερο)',
    topic: 'graphs',
    origin: 'frontistirio',
    source: 'frontistirio-misc',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L06-graphs-i',
      'lectures/L07-graphs-ii',
      'lectures/L08-graphs-iii',
    ],
    sourceFile: '/material/exercises/inclass/3%CE%BF%20%CE%A6%CF%81%CE%BF%CE%BD%CF%84.pdf',
    statement: null,
    solution: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 2024 / 2025 ΕΞΕΤΑΣΤΙΚΕΣ — υψηλή προτεραιότητα
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'exam-june-2025',
    title: 'Εξεταστική Ιουνίου 2025 — Πλήρες θέμα',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2025',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Algorithms-June-2025.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2025',
    title: 'Εξεταστική Σεπτεμβρίου 2025 — Πλήρες θέμα',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'sept-2025',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Algorithms-Sep-2025.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2024',
    title: 'Εξεταστική Ιουνίου 2024 — Πλήρες θέμα',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2024',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Algorithms-June-2024.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2024',
    title: 'Εξεταστική Σεπτεμβρίου 2024 — Πλήρες θέμα',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'sept-2024',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Algorithms-September-2024.pdf',
    statement: null,
    solution: null,
  },

  // ═══════════════════════════════════════════════════════════════════════
  // Παλαιότερα θέματα (Ζησιμόπουλος αρχείο + λοιπά)
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'exam-june-2023',
    title: 'Εξεταστική Ιουνίου 2023 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2023',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2023-June-VZ/Algo-June-2023.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2023',
    title: 'Εξεταστική Σεπτεμβρίου 2023 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'sept-2023',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2023-Sept-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2022',
    title: 'Εξεταστική Ιουνίου 2022 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2022',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2022-June-VZ/Algo_june_2022.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2022',
    title: 'Εξεταστική Σεπτεμβρίου 2022 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'sept-2022',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2022-Sept-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2021',
    title: 'Εξεταστική Ιουνίου 2021 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2021',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2021-June-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-distance-2020',
    title: 'Εξ αποστάσεως εξεταστική 2020',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'distance-2020',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile:
      '/material/exercises/oldtests/%CE%B1%CE%BB%CE%B3%CE%BF%CF%81%CE%B9%CE%B8%CE%BC%CE%BF%CE%B9-%CE%BA%CE%B1%CE%B9-%CF%80%CE%BF%CE%BB%CF%85%CF%80%CE%BB%CE%BF%CE%BA%CE%BF%CF%84%CE%B9%CF%84%CE%B1-%CE%B5%CE%BE-%CE%B1%CF%80%CE%BF%CF%83%CF%84%CE%B1%CF%83%CE%B5%CF%89%CF%82-2020.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2020',
    title: 'Σεπτέμβριος 2020 (Slot 2)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'sept-2020',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile:
      '/material/exercises/oldtests/%CE%91%CE%BB%CE%B3%CE%BF-2020-%CE%A3%CE%B5%CF%80%CF%84-1(Slot2).jpg',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-feb-2019',
    title: 'Φεβρουάριος 2019 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'feb-2019',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2019-Feb-VZ/2019.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2018',
    title: 'Ιούνιος 2018 (Ζησιμόπουλος)',
    topic: 'greedy',
    origin: 'past-exam',
    source: 'june-2018',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2018-June-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2018',
    title: 'Σεπτέμβριος 2018 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'sept-2018',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2018-Sept-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-feb-2017',
    title: 'Φεβρουάριος 2017 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'feb-2017',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile:
      '/material/exercises/oldtests/Zisimopoulos/2017-Feb-VZ/algo-fevr-2017-zisimopoulos.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2017',
    title: 'Σεπτέμβριος 2017 (Ζησιμόπουλος)',
    topic: 'greedy',
    origin: 'past-exam',
    source: 'sept-2017',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2017-Sept-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-feb-2016',
    title: 'Φεβρουάριος 2016 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'feb-2016',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2016-Feb-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2016',
    title: 'Ιούνιος 2016 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'june-2016',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2016-June-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2015',
    title: 'Ιούνιος 2015 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'june-2015',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2015-June-VZ/2015june.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-midterm-2012',
    title: 'Πρόοδος 2012 (Ζησιμόπουλος)',
    topic: 'divide-conquer',
    origin: 'past-exam',
    source: 'midterm-2012',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L01-eisagogika',
      'lectures/L02-asymptotic-analysis',
      'lectures/L03-divide-and-conquer-i',
      'lectures/L04-divide-and-conquer-ii',
      'lectures/L05-divide-and-conquer-iii',
      'lectures/L06-graphs-i',
      'lectures/L07-graphs-ii',
    ],
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2012-Midterm/2012-p.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2011',
    title: 'Ιούνιος 2011 (Ζησιμόπουλος)',
    topic: 'graphs',
    origin: 'past-exam',
    source: 'june-2011',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2011-June-VZ/',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-sept-2011',
    title: 'Σεπτέμβριος 2011 (Ζησιμόπουλος)',
    topic: 'dp',
    origin: 'past-exam',
    source: 'sept-2011',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile:
      '/material/exercises/oldtests/Zisimopoulos/2011-Sept-VZ/%CE%A3%CE%B5%CF%80%CF%84%CE%AD%CE%BC%CE%B2%CF%81%CE%B9%CE%BF%CF%82%202011-VZ.pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-june-2010',
    title: 'Ιούνιος 2010 (Ζησιμόπουλος)',
    topic: 'greedy',
    origin: 'past-exam',
    source: 'june-2010',
    difficulty: 'hard',
    prerequisites: ALL_LECTURES,
    sourceFile:
      '/material/exercises/oldtests/Zisimopoulos/2010-June-VZ/proodos2010(zisimopoulos).pdf',
    statement: null,
    solution: null,
  },
  {
    id: 'exam-midterm-2008',
    title: 'Πρόοδος 2008 (Ζησιμόπουλος)',
    topic: 'divide-conquer',
    origin: 'past-exam',
    source: 'midterm-2008',
    difficulty: 'medium',
    prerequisites: [
      'lectures/L01-eisagogika',
      'lectures/L02-asymptotic-analysis',
      'lectures/L03-divide-and-conquer-i',
      'lectures/L04-divide-and-conquer-ii',
      'lectures/L05-divide-and-conquer-iii',
      'lectures/L06-graphs-i',
    ],
    sourceFile: '/material/exercises/oldtests/Zisimopoulos/2008-Midterm/2008.pdf',
    statement: null,
    solution: null,
  },
]
